data_provider:
  root: /home/yequan/dataset/flowers102
  num_classes: 102
  # root: /home/yequan/dataset/VWW
  # num_classes: 2
  # root: /home/yequan/dataset/stanford_car
  # num_classes: 196

run_config:
  # learning rate
  bs256_lr: 0.1
  n_epochs: 1000
  # optimizer
  # optimizer_name: sgd
  # optimizer_name: sgd_nomom
  # optimizer_name: adam

  # optimizer_name: sgd_scale
  # optimizer_name: sgd_scale_nomom
  optimizer_name: sgd_scale_int_nomom

net_config:
  net_name: mcunet-5fps

backward_config:
  enable_backward_config: 0
  
  # sparse update (100KB scheme): 88.84%
  # enable_backward_config: 1  
  # n_bias_update: 22
  # manual_weight_idx: 21-24-27-30-36-39
  # weight_update_ratio: 1-1-1-1-0.125-0.25

  # update last 12 weights and biases (best setting for last k layers): 87.74%, uses 448KB
  # enable_backward_config: 1 
  # n_bias_update: 12
  # n_weight_update: 12

  # update last 12 biases and FC weight and bias
  # enable_backward_config: 1 
  # n_bias_update: 22
  # n_weight_update: 0


ZO_Estim:
  en: True
  fc_bp: True

  name: ZO_Estim_MC
  # sigma: 1
  n_sample: 1
  signSGD: False

  # trainable_param_list: all
  # trainable_param_list: ['1.7.conv.0.weight']
  trainable_param_list: ['1.13.conv.2.weight']
  # trainable_param_list: ['1.7.conv.0.weight', '1.8.conv.0.weight', '1.9.conv.0.weight', '1.10.conv.0.weight', '1.12.conv.0.weight', '1.13.conv.0.weight']
  # trainable_param_list: ['1.7.conv.0.weight', '1.8.conv.0.weight', '1.9.conv.0.weight', '1.10.conv.0.weight', '1.12.conv.0.weight', '1.13.conv.0.weight', '1.10.conv.1.bias', '1.10.conv.2.bias', '1.11.conv.0.bias', '1.11.conv.1.bias', '1.11.conv.2.bias', '1.12.conv.0.bias', '1.12.conv.1.bias', '1.12.conv.2.bias', '1.13.conv.0.bias', '1.13.conv.1.bias', '1.13.conv.2.bias']
  # trainable_param_list: ['1.10.conv.0.weight', '1.10.conv.1.weight', '1.10.conv.2.weight', '1.11.conv.0.weight', '1.11.conv.1.weight', '1.11.conv.2.weight', '1.12.conv.0.weight', '1.12.conv.1.weight', '1.12.conv.2.weight', '1.13.conv.0.weight', '1.13.conv.1.weight', '1.13.conv.2.weight', '1.10.conv.1.bias', '1.10.conv.2.bias', '1.11.conv.0.bias', '1.11.conv.1.bias', '1.11.conv.2.bias', '1.12.conv.0.bias', '1.12.conv.1.bias', '1.12.conv.2.bias', '1.13.conv.0.bias', '1.13.conv.1.bias', '1.13.conv.2.bias']

  # quantize_method: None
  # sigma: 0.01
  # quantize_method: u_fp-grad_fp
  # quantize_method: u_fp-grad_int

  sigma: 1
  quantize_method: u_int-grad_fp
  # quantize_method: u_int-grad_int

  mask_method: None
  # mask_method: block-30
  # mask_method: layer

  # estimate_method: forward
  estimate_method: antithetic

  obj_fn_type: classifier
  perturb_method: batch

  # obj_fn_type: classifier_row
  # perturb_method: single

  # sample_method: uniform
  # sample_method: gaussian
  # sample_method: bernoulli
  sample_method: coord_basis

  prior_method: None
  # prior_method: last_grad_perturb
  # prior_method: mov_avg_perturb
  # prior_method: last_grad_neighbor
  